ainari/ainari/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard_views.homepage, name='homepage'),
    path('dashboard/', include('dashboard.urls')),
    path('information/', include('information.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ainari/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('paddy_area_detail/<str:paddy_area_name>/', views.paddy_area_detail, name='paddy_area_detail'),
    path('ajax/take_action/', views.take_action, name='take_action'),
    path('create_info', views.create_info, name='create_info'),
    path('test_image', views.test_image, name='test_image'),
    path('test_info', views.test_info, name='test_info'),
    # path('test/', views.test, name='test')
]

ainari/information/urls.py
from django.urls import path, include
from . import views

app_name = 'information'

urlpatterns = [
    path('', views.information, name='information'),
    path('detail/<int:id>/', views.information_detail, name='information_detail'),
    # path('ajax/take_action/', views.take_action, name='take_action'),
    # path('test/', views.test, name='test')
]

ainari/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>AINari</title>
        
        <link rel="stylesheet" href="{% static 'styles.css '%}">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.11.0/css/jquery.dataTables.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <!-- scripts -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>    
        <script src="https://cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js"></script> 
        <script src='{% static "scripts.js" %}'></script>    
        
    </head>
    <body>
        <header class='wrapper'>
            <nav class="navbar navbar-expand-lg">
                <div class="container">
                  <a class="navbar-brand" href="{% url 'homepage' %}">
                      <img src="{% static 'logo.png' %}" alt='AINARI' style='height:70px;'/>
                  </a>

                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>

                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'dashboard:create_info' %}">Create New Paddy Area Information</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'dashboard:test_image' %}">Test Images</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'dashboard:test_info' %}">Test Info</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'information:information' %}">Informations</a>
                      </li>
                      <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">Action</a></li>
                          <li><a class="dropdown-item" href="#">Another action</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                      </li> -->
                      <!-- <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                      </li> -->
                    </ul>
                  </div>
                </div>
            </nav>

        </header>

        <div class='wrapper container mb-5'>
            {% block map %}
            {% endblock %}

            {% block content %}
            {% endblock %}
        </div>
    
    </body>
</html>