ainari/ainari/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dashboard_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard_views.homepage, name='homepage'),
    path('dashboard/', include('dashboard.urls')),
    path('information/', include('information.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ainari/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('paddy_area_detail/<str:paddy_area_name>/', views.paddy_area_detail, name='paddy_area_detail'),
    path('ajax/take_action/', views.take_action, name='take_action'),
    path('create_info', views.create_info, name='create_info'),
    path('test_image', views.test_image, name='test_image'),
    path('test_info', views.test_info, name='test_info'),
    # path('test/', views.test, name='test')
]

ainari/information/urls.py
from django.urls import path, include
from . import views

app_name = 'information'

urlpatterns = [
    path('', views.information, name='information'),
    path('detail/<int:id>/', views.information_detail, name='information_detail'),
    # path('ajax/take_action/', views.take_action, name='take_action'),
    # path('test/', views.test, name='test')
]

ainari/dashboard/models.py
from django.db import models
from information.models import RiskDisease
from django.contrib.auth.models import User

# Create your models here.

class PaddyAreaDetail(models.Model):
    name = models.CharField(max_length=5, unique=True)
    state = models.CharField(max_length=20)
    longitude = models.FloatField()
    latitude = models.FloatField()

    def __str__(self):
        return self.name

    def get_state(self):
        return self.state

class PaddyAreaInfo(models.Model): #child
    date_time = models.DateTimeField(auto_now_add=True)
    paddy_area = models.ForeignKey(PaddyAreaDetail, on_delete=models.CASCADE, default=None)
    paddy_height = models.FloatField()
    humidity = models.FloatField()
    temperature = models.FloatField()
    water_level = models.FloatField()
    soil_nitrogen = models.FloatField(default= 0)
    soil_phosphorus = models.FloatField(default=0)
    soil_potassium = models.FloatField(default=0)
    soil_pH = models.FloatField(default=0)
    rain_fall = models.FloatField(default=0)
    paddy_images = models.ImageField(default='default.png', blank=True, upload_to='info_images')

    #many-to-many
    risk_disease = models.ManyToManyField(RiskDisease, through='PaddyAreaRiskDisease')

    def __str__(self):
        return self.paddy_area.name

#bridges
class PaddyAreaRiskDisease(models.Model): #PAI_D_Intermediate
    risk_disease = models.ForeignKey(RiskDisease, on_delete=models.CASCADE)
    paddy_area_info = models.ForeignKey(PaddyAreaInfo, on_delete=models.CASCADE)
    confidence = models.FloatField()
    happened = models.BooleanField()
    action_taken = models.BooleanField(default=False)

    def get_info_id(self):
        return self.paddy_area_info.id

    def get_disease_name_raw(self):
        return self.risk_disease.name

    def get_disease_name(self):
        return ' '.join([i.capitalize() for i in self.risk_disease.name.split('_')])    

    def get_confidence(self):
        return self.confidence

class TestImage(models.Model):
    paddy_images = models.ImageField(default='default.png', blank=True, upload_to='test_images')

class TestInfo(models.Model):
    humidity = models.FloatField()
    temperature = models.FloatField()
    water_level = models.FloatField()
    soil_nitrogen = models.FloatField(default= 0)
    soil_phosphorus = models.FloatField(default=0)
    soil_potassium = models.FloatField(default=0)
    soil_pH = models.FloatField(default=0)
    rain_fall = models.FloatField(default=0)

ainari/dashboard/forms.py
from django import forms
from . import models
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field

class CreatePaddyAreaInfo(forms.ModelForm):

    class Meta:
        model = models.PaddyAreaInfo
        fields = '__all__'
        exclude = ('risk_disease',)

        labels = {
            'paddy_height': ('Paddy Height (m)'),
            'humidity': ('Humidity (g/kg)'),
            'temperature': ('Temperature (Celcius)'),
            'water_level': ('Water Level (m)'),
            'soil_nitrogen': ('Soil Nitrogen (mg/kg)'),
            'soil_phosphorous': ('Soil Phosphorous (mg/kg)'),
            'soil_potassium': ('Soil Potassium (mg/kg)'),
            'soil_pH': ('Soil pH'),
            'rain_fall': ('Rain Fall (mm)'),
        }
        # help_texts = {
        #     'paddy_height': ('1'),
        # }
        # error_messages = {
        #     'name': {
        #         'max_length': ("This writer's name is too long."),
        #     },
        # }

class TestImage(forms.ModelForm):

    class Meta:
        model = models.TestImage
        fields = ['paddy_images',]

class TestInfo(forms.ModelForm):
    class Meta:
        model = models.TestInfo
        fields = '__all__'

        labels = {
            'humidity': ('Humidity (g/kg)'),
            'temperature': ('Temperature (Celcius)'),
            'water_level': ('Water Level (m)'),
            'soil_nitrogen': ('Soil Nitrogen (mg/kg)'),
            'soil_phosphorous': ('Soil Phosphorous (mg/kg)'),
            'soil_potassium': ('Soil Potassium (mg/kg)'),
            'soil_pH': ('Soil pH'),
            'rain_fall': ('Rain Fall (mm)'),
        }

ainari/dashboard/views.py
from django.shortcuts import render
from django.db.models import Max
from django.http import JsonResponse
from django.shortcuts import redirect 
from django.forms.models import model_to_dict
from django.conf import settings

from .models import PaddyAreaDetail, PaddyAreaInfo, PaddyAreaRiskDisease
from information.models import RiskDiseaseSolutionRelationship, RiskDisease

from . import forms
from . import utils
from . import my_folium

from collections import defaultdict

import os
import time
import requests
import json
import re

ee = False

# Create your views here.
def homepage(request):
    #getting only latest info from each area
    filter_ = PaddyAreaInfo.objects.values('paddy_area').annotate(latest_date=Max('date_time')).order_by('paddy_area')

    paddy_area_info = [ PaddyAreaInfo.objects.get(paddy_area=x['paddy_area'],date_time=x['latest_date'])
                        for x in filter_]

    # queryset = PaddyAreaInfo.objects.filter(id=1)
    # print(queryset.values())
    # print(paddy_area_info)
    #objects
    pd_risk_disease = PaddyAreaRiskDisease.objects.filter(paddy_area_info__in=paddy_area_info)
    rd_solution = RiskDiseaseSolutionRelationship.objects.filter(risk_disease__id__in=pd_risk_disease.values_list('id'))
    # print(rd_solution)

    #ids
    potential_ids = set()
    warning_ids = set()

    # for i in pd_risk_disease.values():
    #     if i['happened'] == True and i['action_taken'] == False:
    #         warning_ids.add(i['paddy_area_info_id'])
    #     elif i['happened'] == False and i['action_taken'] == False:
    #         potential_ids.add(i['paddy_area_info_id'])

    for i in pd_risk_disease.values():
        if i['happened'] == True:
            warning_ids.add(i['paddy_area_info_id'])
        elif i['happened'] == False:
            potential_ids.add(i['paddy_area_info_id'])

    #map
    colour = []
    for i in paddy_area_info:
        if warning_ids or potential_ids:
            if i.id in warning_ids:
                colour.append('red')
            elif i.id in potential_ids:
                colour.append('yellow')
            else:
                colour.append('green')

    #map
    if paddy_area_info != []:
        map_ = my_folium.getMap(ee=ee, paddy_area_info=paddy_area_info, colour=colour)
    else:
        map_ = my_folium.getMap()

    informations = {
        'info': paddy_area_info,
        'pd_risk_disease': pd_risk_disease,
        'rd_solution': rd_solution,
        'potential_ids': potential_ids,
        'warning_ids': warning_ids,
        'map': map_,
    }

    return render(request, 'dashboard/homepage.html', informations)

def paddy_area_detail(request, paddy_area_name):
    paddy_area_info = PaddyAreaInfo.objects.filter(paddy_area__name=paddy_area_name).order_by('-date_time')
    # print(paddy_area_info.values_list('id'))
    #objects
    pd_risk_disease = PaddyAreaRiskDisease.objects.filter(paddy_area_info__id__in = paddy_area_info.values_list('id'))
    # print('rd:', [i.risk_disease.name for i in risk_disease])
    # print('rd:', [i.risk_disease.id for i in risk_disease])
    risk_disease_ids = set([i.risk_disease.id for i in pd_risk_disease]) #the ids of the risk_disease
    # print(risk_disease.values_list('id'))
    rd_solution = RiskDiseaseSolutionRelationship.objects.filter(risk_disease__id__in=risk_disease_ids)
    # print('rd:', rd_solution)
    # print('rd:', [i.solution.name for i in rd_solution])
    rd_ids = set([i['paddy_area_info_id'] for i in pd_risk_disease.values()])
    # print('rd_ids:', rd_ids)

    #maps

    rd_check_colour = PaddyAreaRiskDisease.objects.filter(paddy_area_info=paddy_area_info[0])
    #ids
    potential_ids = set()
    warning_ids = set()

    # for i in rd_check_colour.values():
    #     if i['happened'] == True and i['action_taken'] == False:
    #         warning_ids.add(i['paddy_area_info_id'])
    #     elif i['happened'] == False and i['action_taken'] == False:
    #         potential_ids.add(i['paddy_area_info_id'])

    for i in rd_check_colour.values():
        if i['happened'] == True:
            warning_ids.add(i['paddy_area_info_id'])
        elif i['happened'] == False:
            potential_ids.add(i['paddy_area_info_id'])

    if warning_ids:
        colour = ['red']
    elif potential_ids:
        colour = ['yellow']
    else:
        colour = ['green']

    #map
    if paddy_area_info != []:
        map_ = my_folium.getMap(ee=ee, paddy_area_info=paddy_area_info, colour=colour)
    else:
        map_ = my_folium.getMap()

    informations = {
        'info': paddy_area_info,
        'pd_risk_disease': pd_risk_disease,
        'rd_solution': rd_solution,
        'rd_ids':rd_ids,
        'map': map_,
        'lastest_info': paddy_area_info[0],
    }

    return render(request, 'dashboard/paddy_area_detail.html', informations)

def take_action(request): #get PaddyAreaRiskDisease's ID and modify the action boolean
    #get information
    pard_id = request.POST.get('pard_id')
    next_ = request.POST.get('next')
    action_name = request.POST.get('action_name')

    #call the robot to do something
    
    #update database
    obj = PaddyAreaRiskDisease.objects.get(id=pard_id)
    obj.action_taken = True

    # print('here',obj)
    try:
        obj.save()
        return JsonResponse({"success": True})
    except Exception as e:
        return JsonResponse({"success": False})

def create_info(request):
    if request.method == 'POST':
        form = forms.CreatePaddyAreaInfo(request.POST, request.FILES)
        if form.is_valid():
            
            #save to db
            instance = form.save(commit=True) #true here to save the img to db in order to be retrieved

            #hardcode the path first, future change
            my_image_path = utils.get_image_directory(instance.paddy_images.url)
            print('predicting...')

            # predicting using images
            predictions = utils.resnet_model(my_image_path)

            #predicting using informations
            risk_predictions = utils.model_predict_risk(instance)

            #modelv2
            diseases, probability = utils.get_disease_prob(predictions)
            risk_diseases, risk_probability = utils.get_disease_prob(risk_predictions)

            print('prediction done!')

            #add relationship

            #modelv2 using images
            for i in range(len(diseases)):
                if probability[i] >= 0.5 and diseases[i] != 'healthy':
                    instance.risk_disease.add(RiskDisease.objects.get(name=diseases[i]), 
                                              through_defaults={'confidence':probability[i], 'happened':True})

            #risk using informations
            for i in range(len(risk_diseases)):
                if risk_probability[i] >= 0.5 and risk_diseases[i] != 'healthy':
                    instance.risk_disease.add(RiskDisease.objects.get(name=risk_diseases[i]), 
                                              through_defaults={'confidence':risk_probability[i], 'happened':False})

            #save
            instance.save()
            
            return redirect('dashboard:homepage')

    else:
        form = forms.CreatePaddyAreaInfo()

    return render(request, 'dashboard/create_info.html', {'form': form})

def test_image(request):

    if request.method == 'POST':
        form = forms.TestImage(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=True) #true here to save the img to db in order to be retrieved

            #hardcode the path first, future change

            my_image_path = utils.get_image_directory(instance.paddy_images.url)

            print('predicting...')

            #using kaggle model
            predictions = utils.resnet_model(my_image_path)
            diseases, probability = utils.get_disease_prob(predictions)
            probability = [i*100 for i in probability]

            #using custom vision
            test_pred = utils.custom_vision_model(my_image_path)
            test_diseases, test_probability = utils.get_disease_prob_custom_vision(test_pred)
            test_probability = test_probability * 100
            print('prediction done!')

            info = {
                'image':instance.paddy_images.url,
                'diseases_probability': zip(diseases, probability),
                'custom_vision_diseases': test_diseases, 
                'custom_vision_probability':test_probability,
            }

            return render(request, 'dashboard/test_image.html', {'form': form, 'info': info})
    else:
        form = forms.TestImage()

    return render(request, 'dashboard/test_image.html', {'form': form})

def test_info(request):

    if request.method == 'POST':
        form = forms.TestInfo(request.POST)
        if form.is_valid():
            instance = form.save(commit=True) #true here to save the img to db in order to be retrieved

            print('predicting...')
            risk_predictions = utils.model_predict_risk(instance)
            risk_diseases, risk_probability = utils.get_disease_prob(risk_predictions)
            risk_probability = [i*100 for i in risk_probability]
            print('prediction done!')

            info = {
                'risk_diseases_probability': zip(risk_diseases,risk_probability),
            }

            return render(request, 'dashboard/test_info.html', {'form': form, 'info': info})
    else:
        form = forms.TestInfo()

    return render(request, 'dashboard/test_info.html', {'form': form})

ainari/dashboard/templates/dashboard/create_info.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content%}

<div class='title'>
    <h1> Create Paddy Area Information </h1>
</div>

<form class='site-form' action="{% url 'dashboard:create_info' %}" method="post" enctype='multipart/form-data'>
    {% csrf_token %}

    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            {{ form.paddy_area|as_crispy_field }}
        </div>
    </div>

    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            {{ form.paddy_height|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ form.humidity|as_crispy_field }}
        </div>
    </div>
    
    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            {{ form.temperature|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ form.water_level|as_crispy_field }}
        </div>
    </div>

    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            {{ form.soil_nitrogen|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ form.soil_phosphorous|as_crispy_field }}
        </div>
    </div>

    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            {{ form.soil_potassium|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ form.soil_pH|as_crispy_field }}
        </div>
    </div>

    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            {{ form.rain_fall|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ form.paddy_images|as_crispy_field }}
        </div>
    </div>
    
    <div>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <!-- {{ form|crispy }} -->

    <div class='row justify-content-center' style='margin-bottom:20px;'>
        <button type='submit' class='col-6 submit-button'>Submit</button>
    </div>
</form>

{% endblock %}

ainari/dashboard/templates/dashboard/paddy_area_detail.html
{% extends 'base_layout.html' %}

{% block map %}
    <div class="row justify-content-center">
        <div class="col-6 map-border mb-2 mt-2 pt-2 pb-2">
            {{map|safe}}
        </div>
        <div class="paddy-info table table-striped table-dark col-4 mb-2 mt-2 pt-2 pb-2" style='width:33% !important'>
            <table>
                
                <tr>
                    <td>Humidity:</td>
                    <td>{{lastest_info.humidity}} g/kg</td>
                </tr>
                <tr>
                    <td>Temperature:</td>
                    <td>{{lastest_info.temperature}} celcius</td>
                </tr>
                <tr>
                    <td>Water Level:</td>
                    <td>{{lastest_info.water_level}} m</td>
                </tr>
                <tr>
                    <td>Soil Nitrogen:</td>
                    <td>{{lastest_info.soil_nitrogen}} mg/kg</td>
                </tr>
                <tr>
                    <td>Soil Phosphorus:</td>
                    <td>{{lastest_info.soil_phosphorus}} mg/kg</td>
                </tr>
                <tr>
                    <td>Soil Potassium:</td>
                    <td>{{lastest_info.soil_potassium}} mg/kg</td>
                </tr>
                <tr>
                    <td>Soil pH:</td>
                    <td>{{lastest_info.soil_pH}}</td>
                </tr>
                <tr>
                    <td>RainFall:</td>
                    <td>{{lastest_info.rain_fall}} mm</td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}


{% block content%}

<div class='title'>
    <h1> Paddy Area Details </h1>
</div>

<table id="info_table" class="table table-striped table-dark">
    <thead>
        <tr>
            <!-- <th>ID</th> -->
            <th>DateTime</th>
            <th>Paddy Area</th>
            <th>Lat/Lon</th>
            <th>Image</th>
            <th>RiskDisease-Confidence-Hapenned?</th>
            <th>Information&Solutions</th>
            <th>Action Taken?</th>
        </tr>
    </thead>

    <tbody>
    {% for i in info %}
        <tr>
            <!-- <td>{{i.id}}</td> -->
            <td>{{i.date_time}}</td>
            <td>{{i.paddy_area}}</td>
            <td>{{i.paddy_area.latitude}}/{{i.paddy_area.longitude}}</td>
            <td><img src='{{i.paddy_images.url}}' style="width:100px;height:100px;" /> </td>

            {% if i.id in rd_ids%}
                <td>
                    <ul>
                        {% for d in pd_risk_disease %}
                            {% if d.get_info_id == i.id %}
                            
                                <li>
                                    <p>{{d.get_disease_name}} - {{d.get_confidence}} - {{d.happened}}  </p>
                                </li>
                            {% endif%}
                        {% endfor %}
                    </ul>
                </td>

                <td>
                    <ul>
                        {% for d in pd_risk_disease %}
                            {% if d.get_info_id == i.id %}
                                <li>
                                    <!-- Default dropend button -->
                                    <div class="btn-group dropend"> 
                                        <button type="button" class="dropdown-button dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" >
                                        Actions
                                        </button>
                                        <ul class="dropdown-menu">
                                            <!-- Dropdown menu links -->
                                            <li><a class="dropdown-item" href='{% url "information:information_detail" d.risk_disease.id %}'>More Information</a></li>
                                            
                                            {% for s in rd_solution %}
                                                <!-- <li>{{s.get_solution}}</li> -->
                                                <!-- <li>s.risk_disease.name: {{s.risk_disease.name}}, d.get_disease_name: {{d.get_disease_name}}, </li>
                                                <li>s.happened: {{s.happened}}, d.happened: {{d.happened}}, solution:{{s.get_solution}}</li> -->
                                                
                                                {% if s.risk_disease.name == d.get_disease_name_raw and s.happened == d.happened %}
                                                    {% if d.action_taken == False %}
                                                        <li>
                                                            <form action="" method="post" class='action_button action_taken_{{d.get_info_id}}_{{d.id}}_{{s.id}}'>
                                                            {% csrf_token %}
                                                            <input type="hidden" name="next_{{d.get_info_id}}_{{d.id}}_{{s.id}}" value="{{ request.path }}">
                                                            <input type="hidden" name="action_name_{{d.get_info_id}}_{{d.id}}_{{s.id}}" value="{{s.get_solution}}">
                                                            <input type="hidden" name="pard_id_{{d.get_info_id}}_{{d.id}}_{{s.id}}" value="{{d.id}}">
                                                            <input type="hidden" name="url_{{d.get_info_id}}_{{d.id}}_{{s.id}}" value="{% url 'dashboard:take_action' %}">
                                                            <button type="button" class="dropdown-item">{{s.get_solution}}</button>
                                                            </form>
                                                        </li>
                                                    {% else %}
                                                        <li><a class="dropdown-item disabled" href='#'>{{s.get_solution}}</a></li>
                                                    {% endif %}
                                                    
                                                {% endif%}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </li>
                            {% endif%}
                        {% endfor %}
                    </ul>
                </td>
                
            {% else %}
                <td>No Risk/Disease Detected</td>
                <td>No Action required</td>
            {% endif %}
            
            <td>
                <ul>
                    {% for d in pd_risk_disease %}
                        {% if d.get_info_id == i.id %}
                            <li>
                                <p>{{d.action_taken}}</p>
                            </li>
                        {% endif%}
                    {% endfor %}
                </ul>

            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>


<script type="text/javascript">
    $(document).ready(function() {
        {% for i in info %}
            {% if i.id in rd_ids%}
                {% for d in pd_risk_disease %}
                    {% if d.get_info_id == i.id %}
                        {% for s in rd_solution %}
                            {% if s.risk_disease.name == d.get_disease_name_raw and s.happened == d.happened %}
                                {% if d.action_taken == False %}
                                    
                                $('.action_taken_{{d.get_info_id}}_{{d.id}}_{{s.id}}').click(function(){
                                        next = $('input[name="next_{{d.get_info_id}}_{{d.id}}_{{s.id}}"]').val()
                                        pard_id = $('input[name="pard_id_{{d.get_info_id}}_{{d.id}}_{{s.id}}"]').val()
                                        action_name = $('input[name="action_name_{{d.get_info_id}}_{{d.id}}_{{s.id}}"]').val()
                                        url = $('input[name="url_{{d.get_info_id}}_{{d.id}}_{{s.id}}"]').val()
                                        csrfmiddlewaretoken= $('input[name="csrfmiddlewaretoken"]').val()

                                        $.ajax({
                                            url: url, //which url to send data to
                                            data: {
                                            'csrfmiddlewaretoken': csrfmiddlewaretoken,
                                            'next': next,
                                            'pard_id': pard_id,
                                            'action_name': action_name,
                                            },
                                            type: 'post',
                                            success: function(response){
                                                if (response.success) {
                                                    success_answer = 'ajax call success. ' + action_name + ' is performed.'
                                                    alert(success_answer);
                                                    // window.location=window.location; //reload using this to avoid warning
                                                    window.location.reload()
                                                    // here you update the HTML to change the active to innactive
                                                }else{
                                                    fail_answer = 'ajax call not success. ' + action_name + ' is not performed.'
                                                    alert("ajax call not success.");
                                                }
                                            }
                                        })
                                    })
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endfor %}
});

</script>

{% endblock %}

ainari/dashboard/templates/dashboard/test_image.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block content%}

<div class='title'>
    <h1> Test the paddy images here! </h1>
</div>

<form class='site-form' action="{% url 'dashboard:test_image' %}" method="post" enctype='multipart/form-data'>
    {% csrf_token %}

    <div class="row mb-2 justify-content-center">
        <div class="col-6">
            {{ form.paddy_images|as_crispy_field }}
        </div>
    </div>

    {% if info %}
        <div class="row mb-2 justify-content-center">
            <div class="col-2">
                <img src='{{info.image}}' class="image-border" style="width:200px;height:200px;" />
            </div>
            <div class="col-2">
                <h3>ResNet Prediction</h3>
                {% for disease, prob in info.diseases_probability %}
                    <div class="row mb-1">
                        <p>{{disease}} - {{prob}}%</p>
                    </div>
                {% endfor %}
            </div>
            <div class="col-2">
                <h3>Custom Vision Prediction</h3>
                <div class="row mb-1">
                    <p>{{info.custom_vision_diseases}} - {{info.custom_vision_probability}}%</p>
                </div>
            </div>
        </div>
    {% endif %}

    <div>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <!-- {{ form|crispy }} -->

    <div class='row justify-content-center' style='margin-bottom:20px;'>
        <button type='submit' class='col-6 submit-button'>Submit</button>
    </div>
</form>

{% endblock %}